server:
  port: 8080

spring:
  application:
    name: board2024_boot_jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: project_user
    password: 1234
  servlet:
    multipart:
      max-file-size: 50MB  # ??? ?? ??
      max-request-size: 50MB  # ??? ?? ??
  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
      use_sql_comments: true
    properties:
      hibernate:
        highlight_sql: true
        generate_statistics: true  # SQL ?? ??? ???
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 20  # Batch ?? (??)

logging:
  level:
    org.hibernate.SQL: DEBUG  # Hibernate? ???? SQL ?? ??
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL ???? ??? ??? ???

